//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlive_VRP_Portal.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dCustomer> dCustomer { get; set; }
        public virtual DbSet<dTray> dTray { get; set; }
        public virtual DbSet<dWorkOrder> dWorkOrder { get; set; }
        public virtual DbSet<dWorkorder_Charge> dWorkorder_Charge { get; set; }
        public virtual DbSet<dWorkorder_Comment> dWorkorder_Comment { get; set; }
        public virtual DbSet<dWorkorder_Setup> dWorkorder_Setup { get; set; }
        public virtual DbSet<dCharge> dCharge { get; set; }
        public virtual DbSet<dCode> dCode { get; set; }
        public virtual DbSet<dOVP_Message> dOVP_Message { get; set; }
        public virtual DbSet<dComment> dComment { get; set; }
        public virtual DbSet<dComment_Type_Setup> dComment_Type_Setup { get; set; }
        public virtual DbSet<dOVP_LOOKUPRole> dOVP_LOOKUPRole { get; set; }
        public virtual DbSet<dOVP_SYSUser> dOVP_SYSUser { get; set; }
        public virtual DbSet<dOVP_SYSUserProfile> dOVP_SYSUserProfile { get; set; }
        public virtual DbSet<dOVP_SYSUserRole> dOVP_SYSUserRole { get; set; }
        public virtual DbSet<dRoute> dRoute { get; set; }
        public virtual DbSet<dRoute_Cycle_Date> dRoute_Cycle_Date { get; set; }
        public virtual DbSet<dOVP_Services> dOVP_Services { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> VrpGetNextID(string keyID, string keyTableName, Nullable<decimal> incrementValue)
        {
            var keyIDParameter = keyID != null ?
                new ObjectParameter("KeyID", keyID) :
                new ObjectParameter("KeyID", typeof(string));
    
            var keyTableNameParameter = keyTableName != null ?
                new ObjectParameter("KeyTableName", keyTableName) :
                new ObjectParameter("KeyTableName", typeof(string));
    
            var incrementValueParameter = incrementValue.HasValue ?
                new ObjectParameter("IncrementValue", incrementValue) :
                new ObjectParameter("IncrementValue", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("VrpGetNextID", keyIDParameter, keyTableNameParameter, incrementValueParameter);
        }
    }
}
