//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlive_VRP_Portal.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dCharge
    {
        public string cId { get; set; }
        public string cAccount { get; set; }
        public string cArea_ID { get; set; }
        public string cCycle_ID { get; set; }
        public string cCode { get; set; }
        public string cDescript { get; set; }
        public Nullable<decimal> nUnits { get; set; }
        public Nullable<decimal> nOverride { get; set; }
        public string cReference { get; set; }
        public Nullable<decimal> nFrequency { get; set; }
        public Nullable<decimal> nDiscount { get; set; }
        public Nullable<System.DateTime> dLast_service { get; set; }
        public Nullable<System.DateTime> dNext_service { get; set; }
        public Nullable<System.DateTime> dStart_date { get; set; }
        public Nullable<System.DateTime> dReview_date { get; set; }
        public Nullable<System.DateTime> dLast_review_date { get; set; }
        public Nullable<System.DateTime> dApproved_date { get; set; }
        public string cApproved_user { get; set; }
        public Nullable<System.DateTime> dStop_date { get; set; }
        public string cStop_code_ID { get; set; }
        public string cContract { get; set; }
        public Nullable<decimal> nLinks { get; set; }
        public string mComment { get; set; }
        public string cProrate_type { get; set; }
        public Nullable<System.DateTime> dProrate_date { get; set; }
        public Nullable<bool> lHistory { get; set; }
        public Nullable<decimal> nOld_route { get; set; }
        public string cOld_day { get; set; }
        public string cOld_days { get; set; }
        public string cOld_container { get; set; }
        public Nullable<System.DateTime> tTime_stamp { get; set; }
        public Nullable<decimal> nPrice_Per_Service { get; set; }
    }
}
