//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlive_VRP_Portal.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dCode
    {
        public string cCode { get; set; }
        public string cDescript { get; set; }
        public string cCategory_ID { get; set; }
        public Nullable<decimal> nUnit_price { get; set; }
        public Nullable<decimal> nFactor { get; set; }
        public string cUnit_Of_Measure_ID { get; set; }
        public Nullable<bool> lCredit { get; set; }
        public Nullable<bool> lSuspend { get; set; }
        public Nullable<bool> lContract_required { get; set; }
        public Nullable<bool> lService { get; set; }
        public Nullable<bool> lRental { get; set; }
        public Nullable<bool> lOnly_area_pricing { get; set; }
        public Nullable<bool> lAuto_copy_content_profile { get; set; }
        public Nullable<bool> lAccumulate_volume_stats { get; set; }
        public Nullable<bool> lUnits_required { get; set; }
        public Nullable<bool> lReference_required { get; set; }
        public Nullable<bool> lComment_required { get; set; }
        public Nullable<bool> lVolume_required { get; set; }
        public Nullable<bool> lCost_required { get; set; }
        public string cGl_credit { get; set; }
        public string cGl_debit { get; set; }
        public Nullable<bool> lIs_tax_code { get; set; }
        public Nullable<bool> lTax_1 { get; set; }
        public Nullable<bool> lTax_2 { get; set; }
        public Nullable<bool> lTax_3 { get; set; }
        public Nullable<bool> lTax_4 { get; set; }
        public Nullable<bool> lTax_5 { get; set; }
        public string cLink_type { get; set; }
        public string cLink_code { get; set; }
        public Nullable<decimal> nBreakpoint { get; set; }
        public string cImage_ID { get; set; }
        public string mComment { get; set; }
        public string cReporting_Level_1 { get; set; }
        public string cReporting_Level_2 { get; set; }
        public string cReporting_Level_3 { get; set; }
        public Nullable<System.DateTime> tTime_stamp { get; set; }
        public Nullable<decimal> nPrice_Per_Service { get; set; }
        public Nullable<decimal> nPrice_Per_Service_Factor { get; set; }
    }
}
