//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlive_VRP_Portal.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dComment_Type_Setup
    {
        public string cID { get; set; }
        public string cDescript { get; set; }
        public Nullable<bool> lPin_note { get; set; }
        public Nullable<bool> lStatement { get; set; }
        public Nullable<bool> lRoute { get; set; }
        public Nullable<bool> lComment_required { get; set; }
        public string cImage_ID { get; set; }
        public string cAuto_link_entity { get; set; }
        public string mPredefined { get; set; }
        public Nullable<decimal> nThru_date_interval { get; set; }
        public Nullable<System.DateTime> tTime_stamp { get; set; }
    }
}
