//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlive_VRP_Portal.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dCustomer
    {
        public string cAccount { get; set; }
        public string cOld_Account { get; set; }
        public Nullable<bool> lMaster_billing { get; set; }
        public string cBill_account { get; set; }
        public string cUser_num { get; set; }
        public string cName { get; set; }
        public string cName_2 { get; set; }
        public string cAddress_1 { get; set; }
        public string cAddress_2 { get; set; }
        public string cCity { get; set; }
        public string cState { get; set; }
        public string cZip { get; set; }
        public Nullable<System.DateTime> dZip_date { get; set; }
        public string cZip_barcode { get; set; }
        public string cCarrier_rt { get; set; }
        public string cPhone { get; set; }
        public string cFax { get; set; }
        public string cContact { get; set; }
        public string cE_mail { get; set; }
        public string cSite_name { get; set; }
        public string cSite_street_number { get; set; }
        public string cSite_street_name { get; set; }
        public string cSite_street_suffix { get; set; }
        public string cSite_address { get; set; }
        public string cSite_city { get; set; }
        public string cSite_state { get; set; }
        public string cSite_zip { get; set; }
        public string cSite_phone { get; set; }
        public string cSite_fax { get; set; }
        public string cSite_contact { get; set; }
        public string cSite_e_mail { get; set; }
        public string cArea_ID { get; set; }
        public string cType_ID { get; set; }
        public string cCycle_ID { get; set; }
        public string cTax_Table_ID { get; set; }
        public string cGroup_ID { get; set; }
        public string cSystem_ID { get; set; }
        public string cStatus_ID { get; set; }
        public string cNew_status_ID { get; set; }
        public Nullable<System.DateTime> dNew_status_date { get; set; }
        public string cIndex_type { get; set; }
        public Nullable<System.DateTime> dStart { get; set; }
        public Nullable<System.DateTime> dReview { get; set; }
        public Nullable<System.DateTime> dSuspend { get; set; }
        public Nullable<System.DateTime> dRestart { get; set; }
        public Nullable<System.DateTime> dStop { get; set; }
        public string cRecycle { get; set; }
        public string cMap1 { get; set; }
        public string cMap2 { get; set; }
        public string cMap3 { get; set; }
        public string cGeocode { get; set; }
        public string cLongitude { get; set; }
        public string cLatitude { get; set; }
        public string cMap_other { get; set; }
        public Nullable<decimal> nUnbilled { get; set; }
        public Nullable<decimal> nCurrent { get; set; }
        public Nullable<decimal> nThirty { get; set; }
        public Nullable<decimal> nSixty { get; set; }
        public Nullable<decimal> nNinety { get; set; }
        public Nullable<decimal> nOne_twenty { get; set; }
        public Nullable<decimal> nBalance { get; set; }
        public Nullable<decimal> nLate_charg { get; set; }
        public string cLate_start { get; set; }
        public Nullable<decimal> nLast_l_chg { get; set; }
        public Nullable<decimal> nComputd_on { get; set; }
        public Nullable<System.DateTime> dLast_late_charge_date { get; set; }
        public string cNotice_start { get; set; }
        public Nullable<decimal> nLast_notic { get; set; }
        public Nullable<System.DateTime> dLast_notice_date { get; set; }
        public Nullable<decimal> nLast_paid { get; set; }
        public Nullable<System.DateTime> dDate_paid { get; set; }
        public string cPurchase_order { get; set; }
        public Nullable<System.DateTime> dPo_expires { get; set; }
        public Nullable<decimal> nCr_limit { get; set; }
        public Nullable<decimal> nDeposit { get; set; }
        public Nullable<System.DateTime> dDepos_date { get; set; }
        public Nullable<bool> lContract_required { get; set; }
        public Nullable<bool> lBank_eft { get; set; }
        public string cBank_ID { get; set; }
        public string cBank_acct { get; set; }
        public string cBank_drawr { get; set; }
        public string cCurrent_invoice { get; set; }
        public string cChanges { get; set; }
        public string cUser_1 { get; set; }
        public string cUser_2 { get; set; }
        public string cUser_3 { get; set; }
        public string cUser_4 { get; set; }
        public string cUser_5 { get; set; }
        public Nullable<decimal> nInvoices { get; set; }
        public Nullable<decimal> nComments { get; set; }
        public Nullable<decimal> nServicelinks { get; set; }
        public Nullable<decimal> nCharges { get; set; }
        public Nullable<decimal> nRoutes { get; set; }
        public Nullable<decimal> nContainers { get; set; }
        public Nullable<decimal> nContracts { get; set; }
        public Nullable<decimal> nWorkorders { get; set; }
        public Nullable<bool> lRequires_financial_approval { get; set; }
        public Nullable<bool> lRequires_operations_approval { get; set; }
        public Nullable<System.DateTime> dLast_servc { get; set; }
        public string cProrate_type { get; set; }
        public Nullable<System.DateTime> dProrate_date { get; set; }
        public Nullable<System.DateTime> tTime_stamp { get; set; }
        public string cSite_ID { get; set; }
        public string cCell_Phone { get; set; }
        public string cSite_Cell_Phone { get; set; }
        public Nullable<bool> lEmail_Statement { get; set; }
        public Nullable<bool> lEmail_Only_Statement { get; set; }
    }
}
