//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlive_VRP_Portal.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dOVP_Message
    {
        public string cMessageID { get; set; }
        public string cAccount { get; set; }
        public string cArea_ID { get; set; }
        public string cSubject { get; set; }
        public string cMessage { get; set; }
        public Nullable<System.DateTime> dDate { get; set; }
    }
}
