//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlive_VRP_Portal.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dOVP_Services
    {
        public int ServID { get; set; }
        public string ServTitle { get; set; }
        public string ServDescription { get; set; }
        public string ServType { get; set; }
    }
}
