//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlive_VRP_Portal.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dRoute
    {
        public string cID { get; set; }
        public string cAccount { get; set; }
        public string cRoute_ID { get; set; }
        public Nullable<decimal> nSequence { get; set; }
        public Nullable<System.DateTime> dStart_date { get; set; }
        public Nullable<System.DateTime> dStop_date { get; set; }
        public string cRoute_Cycle_ID { get; set; }
        public Nullable<bool> lActive { get; set; }
        public string cLink_ID { get; set; }
        public Nullable<System.DateTime> tTime_stamp { get; set; }
        public string cAlt_Route_ID { get; set; }
        public Nullable<decimal> nAlt_Sequence { get; set; }
        public string cBearing { get; set; }
        public string cGeo_Index { get; set; }
        public string cLatitude { get; set; }
        public string cLongitude { get; set; }
        public string cOnRoute_1 { get; set; }
        public string cOnRoute_2 { get; set; }
        public string cService_Window_1_Start_Time { get; set; }
        public string cService_Window_1_End_Time { get; set; }
        public string cService_Window_2_Start_Time { get; set; }
        public string cService_Window_2_End_Time { get; set; }
        public string cService_No_Service_Start_Time { get; set; }
        public string cService_No_Service_End_Time { get; set; }
    }
}
