//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlive_VRP_Portal.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dTray
    {
        public string cID { get; set; }
        public string cTray_ID { get; set; }
        public Nullable<bool> lSend { get; set; }
        public Nullable<bool> lPriority { get; set; }
        public Nullable<bool> lAuto_show { get; set; }
        public Nullable<bool> lComplete { get; set; }
        public Nullable<System.DateTime> dCreate_date { get; set; }
        public string cCreate_time { get; set; }
        public Nullable<System.DateTime> dSend_date { get; set; }
        public string cSend_time { get; set; }
        public Nullable<System.DateTime> dSchedule_date { get; set; }
        public string cSchedule_time { get; set; }
        public Nullable<System.DateTime> dComplete_date { get; set; }
        public string cComplete_time { get; set; }
        public string cFrom_user_id { get; set; }
        public string cTo_Tray_ID { get; set; }
        public string cSend_Tray_ID { get; set; }
        public string cAccount { get; set; }
        public string cEntity_id { get; set; }
        public string cSource_ID { get; set; }
        public Nullable<bool> lForward_email { get; set; }
        public string cSubject { get; set; }
        public string mComment { get; set; }
        public Nullable<System.DateTime> tTime_stamp { get; set; }
    }
}
