//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlive_VRP_Portal.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dWorkOrder
    {
        public Nullable<bool> lSelected { get; set; }
        public string cSelected_user { get; set; }
        public string cAccount { get; set; }
        public string cSite_name { get; set; }
        public string cSite_address { get; set; }
        public Nullable<System.DateTime> dSchd_dt { get; set; }
        public string cSchd_time { get; set; }
        public string cWorkorder { get; set; }
        public string cWorkorder_Type { get; set; }
        public string cLevel { get; set; }
        public string cDepartment_ID { get; set; }
        public string cService_description { get; set; }
        public string cContract_ID { get; set; }
        public string cPurchase_order { get; set; }
        public string cInvoice { get; set; }
        public string cUser_cod { get; set; }
        public Nullable<bool> lPrinted { get; set; }
        public Nullable<bool> lRequired_check_passed { get; set; }
        public Nullable<bool> lCompleted { get; set; }
        public string cAcct_Route_ID { get; set; }
        public string cRoute_ID { get; set; }
        public string cTransporter_ID { get; set; }
        public string cVehicle_ID { get; set; }
        public Nullable<decimal> nOdom_out { get; set; }
        public Nullable<decimal> nOdom_in { get; set; }
        public string cReceiver_ID { get; set; }
        public string cDocket_ID { get; set; }
        public Nullable<decimal> nVolume { get; set; }
        public string cUnit_Of_Measure_ID { get; set; }
        public Nullable<decimal> nLf_cost { get; set; }
        public Nullable<System.DateTime> dCritical_date { get; set; }
        public string cCritical_start_time { get; set; }
        public string cCritical_end_time { get; set; }
        public Nullable<decimal> nCritical_duration { get; set; }
        public Nullable<decimal> nTotal_cost { get; set; }
        public Nullable<decimal> nTotal_revenue { get; set; }
        public Nullable<decimal> nProfit { get; set; }
        public Nullable<bool> lBatch_created { get; set; }
        public Nullable<decimal> nSequence { get; set; }
        public string cCroute_fk { get; set; }
        public Nullable<System.DateTime> tTime_stamp { get; set; }
        public string cCanceled_Level { get; set; }
        public string cWO_User_Character_1 { get; set; }
        public string cWO_User_Character_2 { get; set; }
        public string cWO_User_Character_3 { get; set; }
        public Nullable<bool> lWO_User_Checkbox_1 { get; set; }
        public Nullable<bool> lWO_User_Checkbox_2 { get; set; }
        public Nullable<bool> lWO_User_Checkbox_3 { get; set; }
        public Nullable<System.DateTime> dWO_User_Date_1 { get; set; }
        public Nullable<System.DateTime> dWO_User_Date_2 { get; set; }
        public Nullable<System.DateTime> dWO_User_Date_3 { get; set; }
        public Nullable<decimal> nWO_User_Number_1 { get; set; }
        public Nullable<decimal> nWO_User_Number_2 { get; set; }
        public Nullable<decimal> nWO_User_Number_3 { get; set; }
        public string mWO_User_Memo_1 { get; set; }
        public string mWO_User_Memo_2 { get; set; }
        public string mWO_User_Memo_3 { get; set; }
        public Nullable<decimal> nDuration { get; set; }
        public string cInterval_ID { get; set; }
        public string cSeries_ID { get; set; }
    }
}
