//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlive_VRP_Portal.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dWorkorder_Comment
    {
        public string cID { get; set; }
        public string cWorkorder { get; set; }
        public string cContract_ID { get; set; }
        public string cComment_ID { get; set; }
        public Nullable<bool> lCreate_comment { get; set; }
        public Nullable<decimal> nOrder { get; set; }
        public string cComment_Type_ID { get; set; }
        public string mComment { get; set; }
        public string cCreated_Comment_ID { get; set; }
        public string cWorkorder_Setup_ID { get; set; }
        public Nullable<bool> lProcessed { get; set; }
        public Nullable<System.DateTime> tTime_stamp { get; set; }
    }
}
